<div id="login-page" class="login-page flex-container">
    <div id="login-box" class="login-box flex-container">
        <span></span>
        <form method="post" action="../administrator">
            <label for="username">Username:</label><br>
            <input type="text" id="username" name="username"></input><br>
            <label for="password">Password:</label><br>
            <input type="password" id="password" name="password"></input><br><br>
            <input type="submit" value="Login">
        </form>
    </div>
</div>

<style>
    .flex-container {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .login-page {
        background-color: #E3E3E3;
        width: 100vw;
        height: 100vh;
    }

    .login-box {
        width: 40%;
        height: 20%;
    }
</style>