<?php
$failed = false;
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    if (isset($_POST["password"])) {
        $temp_password = password_hash("asc_adm1n", PASSWORD_DEFAULT);
        if (password_verify($_POST["password"], $temp_password)) {
            if (session_status() != PHP_SESSION_ACTIVE) {
                 session_start();
            }
            $_SESSION["id"] = session_create_id();
            wp_safe_redirect(home_url("/admin-page/"));
        } else {
            $failed = true;
        }
    }
}
?>

<link rel="stylesheet" href="<?php echo PLUGIN_TEMPLATE_PLUGIN_URL . "public/css/login.css"; ?>">
	<div class="login-wrapper">
		<div class="login-box">

			<div class="login-title">ASC Admin Login</div>

			<form method="post" action="">
				<label>Password</label>
				<input type="password" name="password" required>
				<button type="submit">Log In</button>
			</form>
			<?php
			if ($failed) {
				echo "<span class=\"fail\">Incorrect Password</span>";	
			}
			?>

			<p class="login-warning">
				<strong>Important:</strong> Access beyond this point is restricted to authorized users only.
			</p>

		</div>
	</div>